apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista
spec:
  template:
    spec:
      containers:
      - name: user-container
        image: image-registry.openshift-image-registry.svc:5000/wk12-dev-coffeeshop/barista:latest

