apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista
spec:
  template:
    spec:
      containers:
      - name: user-container
        image: NEXUS_REGISTRY_HOSTNAME/GUID-barista:prod-2021-04-23-14-10-26

