apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barista
  namespace: r974b-argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: r974b-prod-coffeeshop
  project: coffee-shop
  source:
    path: ./coffee-shop-kustomize/barista/overlays/production
    repoURL: http://homework-gitea.gpte-hw-cicd.svc:3000/lbarry-redhat.com-r974b/coffee-shop-final-lab.git
    targetRevision: HEAD
