apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop
  namespace: wk12-prod-coffeeshop
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: wk12-prod-coffeeshop
  project: coffee-shop
  source:
    path: ./coffee-shop-kustomize/coffee-shop/overlays/production
    repoURL: https://homework-gitea.apps.shared-dev4.dev4.openshift.opentlc.com/wkulhane-redhat.com/coffee-shop-final-lab.git
    targetRevision: HEAD
