apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop-pipeline
  namespace: r974b-argocd
spec:
  destination:
    namespace: r974b-pipeline
    server: https://kubernetes.default.svc
  project: coffee-shop
  source:
    path: ./coffee-shop-pipeline
    repoURL: http://homework-gitea.gpte-hw-cicd.svc:3000/lbarry-redhat.com-r974b/coffee-shop-final-lab.git
    targetRevision: HEAD

