---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./coffee-shop-database.yaml
- ./coffee-shop.yaml
- ./coffee-shop-dev.yaml
- ./barista.yaml
- ./barista-dev.yaml
- ./coffee-shop-pipeline.yaml

patches:
- path: ./syncpolicy-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: barista
- path: ./syncpolicy-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: coffee-shop-database
- path: ./syncpolicy-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: coffee-shop
- path: ./syncpolicy-patch.yaml
  target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: coffee-shop-app-of-apps
