apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-quarkus-application
spec:
  params:
  - name: DEPLOY_SERVERLESS
    type: string
    description: Flag to indicate whether to run deploy-serverless step or not
    default: "false"
  - name: APP_NAME
    type: string
    description: App name must be coffee-shop or barista
    default: coffee-shop
  - name: NAMESPACE
    type: string
    description: Namespace to which to deploy the application
    default: fcrp7-dev-coffeeshop
  - name: IMAGE
    type: string
    description: Iamge name, including tag
    default: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/$(params.APP_NAME):dev-$(tasks.generate-tag.results.image-tag)


  tasks:

  - name: set-image-in-deployment
    when:
      - input: "$(params.DEPLOY_SERVERLESS)"
        operator: in
        values: ["false"]
    timeout: "0h1m0s"
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: ARGS
      value:
      - set
      - image
      - deployment
      - $(params.APP_NAME)
      - $(params.APP_NAME)=$(params.IMAGE)
      - -n $(params.NAMESPACE)

  - name: set-image-in-knative
    when:
      - input: "$(params.DEPLOY_SERVERLESS)"
        operator: in
        values: ["true"]
    timeout: "0h1m0s"
    taskRef:
      kind: ClusterTask
      name: kn
    params:
    - name: ARGS
      value:
      - "service"
      - "update"
      - "$(params.APP_NAME)"
      - "--image=$(params.IMAGE)"
      - "--no-wait"
      - "--namespace"
      - "$(params.NAMESPACE)"