apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-quarkus-application
spec:
  params:
  - name: DEPLOY_Stkn pipeline start build-and-deploy-quarkus-application \
    --use-param-defaults \
    --param APP_NAME=coffee-shop \
    --param KUSTOMIZE_GIT_CONTEXT_DIR=coffee-shop-kustomize/coffee-shop \
    --param KUSTOMIZE_GIT_FILE_NAME=overlays/production/deployment-patches.yaml \
    --workspace name=app-source,claimName=workspace-pvc \
    --workspace name=maven-settings,emptyDir= \
    --workspace name=images-url,emptyDir= \
    --pod-template=$HOME/coffee-shop-final-lab/coffee-shop-pipeline/pod-template.yaml \
    --showlog \
    -n ${PREFIX}-pipelineERVERLESS
    type: string
    description: Flag to indicate whether to run deploy-serverless step or not
    default: "false"
  - name: APP_NAME
    type: string
    description: App name must be coffee-shop or barista
    default: coffee-shop
  - name: NAMESPACE
    type: string
    description: Namespace to which to deploy the application
    default: fcrp7-dev-coffeeshop
  - name: IMAGE
    type: string
    description: Iamge name, including tag
    default: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/$(params.APP_NAME):dev-$(tasks.generate-tag.results.image-tag)

  results:
  - name: image-tag
    description: The Production Image Tag
    value: dev-$(tasks.generate-tag.results.image-tag)


  tasks:

  - name: set-image-in-deployment
    when:
      - input: "$(params.DEPLOY_SERVERLESS)"
        operator: in
        values: ["false"]
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: ARGS
      value:
      - set
      - image
      - deployment
      - $(params.APP_NAME)
      - $(params.APP_NAME)=$(params.IMAGE)
      - -n $(params.NAMESPACE)

  - name: set-image-in-knative
    when:
      - input: "$(params.DEPLOY_SERVERLESS)"
        operator: in
        values: ["true"]
    taskRef:
      kind: ClusterTask
      name: kn
    params:
    - name: ARGS
      value:
      - service
      - update
      - $(params.APP_NAME)
      - "--image=$(params.IMAGE)"
      - -n $(params.NAMESPACE)